### ISSUE TITLE
Compile fails with Varnish 5.2

### ISSUE THREAD

**Issue by tavisma** [Dridi/libvmod-querystring#36]
Compiles and works in the same environment with 4.1 installed,
```
make
make  all-recursive
make[1]: Entering directory `/etc/varnish/vmods/vmod-querystring-1.0.3'
Making all in src
make[2]: Entering directory `/etc/varnish/vmods/vmod-querystring-1.0.3/src'
  CC       vmod_querystring.lo
vmod_querystring.c: In function ‘qs_truncate’:
vmod_querystring.c:37:7: error: assignment makes pointer from integer without a cast [-Werror]
   tmp = WS_Snapshot(ws); \
       ^
vmod_querystring.c:114:3: note: in expansion of macro ‘WS_ClearOverflow’
   WS_ClearOverflow(ws, res);
   ^
vmod_querystring.c:114:3: error: passing argument 2 of ‘WS_Reset’ makes integer from pointer without a cast [-Werror]
In file included from vmod_querystring.c:28:0:
/usr/include/varnish/cache/cache.h:1057:6: note: expected ‘uintptr_t’ but argument is of type ‘char *’
 void WS_Reset(struct ws *ws, uintptr_t);
      ^
vmod_querystring.c: In function ‘qs_apply’:
vmod_querystring.c:37:7: error: assignment makes pointer from integer without a cast [-Werror]
   tmp = WS_Snapshot(ws); \
       ^
vmod_querystring.c:284:3: note: in expansion of macro ‘WS_ClearOverflow’
   WS_ClearOverflow(ctx->ws, res);
   ^
vmod_querystring.c:284:3: error: passing argument 2 of ‘WS_Reset’ makes integer from pointer without a cast [-Werror]
In file included from vmod_querystring.c:28:0:
/usr/include/varnish/cache/cache.h:1057:6: note: expected ‘uintptr_t’ but argument is of type ‘char *’
 void WS_Reset(struct ws *ws, uintptr_t);
      ^
vmod_querystring.c:347:3: error: passing argument 2 of ‘WS_Reset’ makes integer from pointer without a cast [-Werror]
   WS_Reset(ctx->ws, res);
   ^
In file included from vmod_querystring.c:28:0:
/usr/include/varnish/cache/cache.h:1057:6: note: expected ‘uintptr_t’ but argument is of type ‘char *’
 void WS_Reset(struct ws *ws, uintptr_t);
      ^
vmod_querystring.c:362:2: error: passing argument 2 of ‘WS_Reset’ makes integer from pointer without a cast [-Werror]
  WS_Reset(ctx->ws, cur);
  ^
In file included from vmod_querystring.c:28:0:
/usr/include/varnish/cache/cache.h:1057:6: note: expected ‘uintptr_t’ but argument is of type ‘char *’
 void WS_Reset(struct ws *ws, uintptr_t);
      ^
vmod_querystring.c: At top level:
cc1: error: unrecognized command line option "-Wno-int-conversion" [-Werror]
cc1: all warnings being treated as errors
make[2]: *** [vmod_querystring.lo] Error 1
make[2]: Leaving directory `/etc/varnish/vmods/vmod-querystring-1.0.3/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/etc/varnish/vmods/vmod-querystring-1.0.3'
make: *** [all] Error 2
```

**Comment by tavisma** [comment]
Seems to break with 5.1.3 as well

**Comment by Dridi** [comment]
When you run the configure script, there's a short recap at the end, could you please share the output for both 5.1.3 and 5.2?

I don't see any problems building 1.0.3 against both 5.1.3 and 5.2 on my system:

```
$ ./configure
[...]

        ==== libvmod-querystring 1.0.3 ====

        varnish:      5.2.0
        prefix:       /opt/varnish-5.2.0
        vmoddir:      /opt/varnish-5.2.0/lib/varnish/vmods

        compiler:     gcc
        cflags:       -g -O2 -Wno-int-conversion
        ldflags:      
        warnings:     [...]

$ make -s
config.status: creating config.h
config.status: config.h is unchanged
Making all in src
  VMODTOOL vcc_querystring_if.c
  CC       vmod_querystring.lo
  CC       vcc_querystring_if.lo
  CCLD     libvmod_querystring.la
  GEN      vmod_querystring.3
```

I'll try again later on el7, thanks for reporting.

**Comment by tavisma** [comment]
Sorry for the delay

```
	==== libvmod-querystring 1.0.3 ====

	varnish:      5.1.3
	prefix:       /usr
	vmoddir:      /usr/lib64/varnish/vmods

	compiler:     gcc -std=gnu99
	cflags:       -g -O2 -Wno-int-conversion
	ldflags:      
	warnings:     -fno-strict-aliasing -Wall -Wextra -Wundef -Wnested-externs -Wwrite-strings -Wpointer-arith -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wredundant-decls -Wno-unused-parameter -Wno-missing-field-initializers -Wdeclaration-after-statement -Wformat=2 -Wold-style-definition -Wcast-align -Wformat-nonliteral -Wformat-security -Wsign-compare -Wstrict-aliasing -Wshadow -Winline -Wpacked -Wmissing-format-attribute -Wmissing-noreturn -Winit-self -Wmissing-include-dirs -Wunused-but-set-variable -Warray-bounds -Wimplicit-function-declaration -Wreturn-type -Wswitch-enum -Wswitch-default -Werror -Wno-suggest-attribute=format -Wno-error=unused-parameter -Wno-error=missing-field-initializers

	==== libvmod-querystring 1.0.3 ====

	varnish:      5.2.0
	prefix:       /usr
	vmoddir:      /usr/lib64/varnish/vmods

	compiler:     gcc -std=gnu99
	cflags:       -g -O2 -Wno-int-conversion
	ldflags:      
	warnings:     -fno-strict-aliasing -Wall -Wextra -Wundef -Wnested-externs -Wwrite-strings -Wpointer-arith -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wredundant-decls -Wno-unused-parameter -Wno-missing-field-initializers -Wdeclaration-after-statement -Wformat=2 -Wold-style-definition -Wcast-align -Wformat-nonliteral -Wformat-security -Wsign-compare -Wstrict-aliasing -Wshadow -Winline -Wpacked -Wmissing-format-attribute -Wmissing-noreturn -Winit-self -Wmissing-include-dirs -Wunused-but-set-variable -Warray-bounds -Wimplicit-function-declaration -Wreturn-type -Wswitch-enum -Wswitch-default -Werror -Wno-suggest-attribute=format -Wno-error=unused-parameter -Wno-error=missing-field-initializers
```

**Comment by tavisma** [comment]
Let me know if i can provide any additional information

**Comment by tavisma** [comment]
Were you able to reproduce this issue?

**Comment by ingvarha** [comment]
By adding this before running make, yes.

  sed -i 's/-Werror//g;' src/Makefile

Ingvar

**Comment by ingvarha** [comment]
I mean, if I /don't/ remove -Werror, it will fail  :-)

**Comment by ingvarha** [comment]
[build.log](https://github.com/Dridi/libvmod-querystring/files/1435577/build.log)

**Comment by ingvarha** [comment]
[build.log](https://github.com/Dridi/libvmod-querystring/files/1435600/build.log)

el7 mock build

**Comment by Dridi** [comment]
Thank you for your patience, I hope you still have some left...

I finally found some time to sit down and take care of this and other things about the build system that I've wanted to fix for a while now. While this is still work in progress, please give it a try and confirm whether it works for you too:

https://dridi.fedorapeople.org/vmod-querystring-1.0.3.tar.gz

**Comment by tavisma** [comment]
We appreciate the assistance!
We used the @ingvarha patch/sed and so far havn't run into problems with it

This new version seems to compile, run and passes some basic validation tests
I'll follow up if we encounter any strangeness

**Comment by Dridi** [comment]
I didn't change anything to the VMOD, only the build system.

Thanks for confirming!
